### ISSUE TITLE
Dump tests only if they've been changed

### ISSUE THREAD

**Issue by albert12132** [Cal-CS-61A-Staff/ok-client#10]
The best way to do this is to add a `modified` property method in the `Serializable` class. Simply having __setattr__ toggle an attribute is probably not enough; consider creating a "snapshot" of the initialization and comparing when dumping tests.

**Comment by knrafto** [comment]
As @kvchen brought up recently, I'd rather see the test progress being tracked in a separate file so that tests don't have to be rewritten. It's especially annoying when the test files are under version control, since OK will reformat the tests during each run.

**Comment by knrafto** [comment]
Closing in favor of #194
