### ISSUE TITLE
Add a "default tests" field to *.ok config

### ISSUE THREAD

**Issue by albert12132** [Cal-CS-61A-Staff/ok-client#100]
Allow staff members to specify which tests are "default", i.e. which tests to include when `python3 ok` is run with no `-q` flags. It is not always desired to run all tests that were loaded.

If "default tests" is not specified, the default should be all tests.

**Comment by papajohn** [comment]
Is the purpose of this change to avoid running tests against extra questions in lab?

**Comment by albert12132** [comment]
Yes.
