### ISSUE TITLE
ExportProtocol options

### ISSUE THREAD

**Issue by soumyabasu** [Cal-CS-61A-Staff/ok-client#107]
I think ExportProtocol should be built out to have more options and support a bunch of queries (similar to the search feature on our website). Two additional queries that might be useful are:
- Getting all submissions and putting it in the local directory. It probably won't take much longer than getting the latest submission to run.
- Getting all of the backups for a particular student- I don't think I sent this script to you so let me know if you want it.

**Comment by knrafto** [comment]
Export protocol is now dead.
