### ISSUE TITLE
Student Interface Improvements

### ISSUE THREAD

**Issue by soumyabasu** [Cal-CS-61A-Staff/ok-client#114]
A couple of ways to improve the student interface. Most of these fall into giving more feedback on what is wrong with the student answer:
- Remove the type of error from the unlocking (e.g. accept 'Error', 'ERROR', 'error' when it's an IndexError)
- Give information on the types.

Not entirely sure if the hint system will be a useful addition though.

**Comment by knrafto** [comment]
Mostly resolved. Closing in favor of #213
