### ISSUE TITLE
Export Protocol Timeouts 

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok-client#119]
This might have to do with the size of the student list when exporting grades. It worked once when I bumped the timeout so I thought increasing the timeout that would help - but it doesn't appear to be consistent. 

Traceback

```
  File "ok/client/protocols/export.py", line 37, in run
  File "ok/client/protocols/export.py", line 143, in get_students
  File "ok/client/protocols/export.py", line 138, in request
  File "ok/client/utils/network.py", line 24, in api_request
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
...
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ssl.py", line 623, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
```

**Comment by soumyabasu** [comment]
How about a dynamic timeout? Maybe start with a short timeout and just multiply by 2 (or a higher factor)?

**Comment by jathak** [comment]
The timeout for `ExportProtocol` is hard-coded in `utils/network.py`. Should this be changed to respond to a command line argument? Or should the timeout change based on what is being requested. Right now, all API requests have a 15 second timeout, but it might make more sense to have a longer timeout for getting the student list but keep the current timeout (or a shorter timeout) for other requests.

**Comment by soumyabasu** [comment]
> Should this be changed to respond to a command line argument? Or should the timeout change based on what is being requested?

I don't think the command line should set timeouts since the program should "just work". I think the latter option is a good one.

However, I'm not sure if this is a server side error since I remember seeing an issue about this there. @Sumukh - can you clarify?

**Comment by knrafto** [comment]
Export protocol is now gone
