### ISSUE TITLE
Warn/Error if using 32 bit python on OSX

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok-client#120]
Using 32 bit Python3 on OSX causes SSL issues. We should 
- [x] log this information in debug. 
- [x] warn the user that authentication may not work and prompt them to install python3 x64 instead.

**Comment by Sumukh** [comment]
Bump.
This is the relevant code: 
```
import struct
bit_v = (8 * struct.calcsize("P"))
```

**Comment by brianhou** [comment]
@haydensheung, do you have time to do this today?

**Comment by haydensheung** [comment]
Wait sorry for missing this, but I am bit lost... Would you mind clarifying what should I do?

**Comment by Sumukh** [comment]
Use the code snippet I provided above to check that they are using 64 bit version. You would want to edit the main method of `cli/ok.py`. If they are using a 32bit version - you want to log it (see the file for how to log messages) and print a message to the user that 32bit python is not supported and that they should install the 64bit version.

**Comment by haydensheung** [comment]
I see, so `bit_v` is the bit version they are using, correct?

**Comment by Sumukh** [comment]
yes - it's an integer.

**Comment by haydensheung** [comment]
Okay, I will work on that now! Thanks!

**Comment by Sumukh** [comment]
Resolved in #153
