### ISSUE TITLE
AnalyticsProtocol seems slow

### ISSUE THREAD

**Issue by brianhou** [Cal-CS-61A-Staff/ok-client#121]
The culprit seems to be `snippets = self.RE_SNIPPET.findall(lines)` in https://github.com/Cal-CS-61A-Staff/ok-client/blob/master/client/protocols/analytics.py#L62.

This search takes my computer ~12 seconds for the Hog project.

**Comment by brianhou** [comment]
Hm, upon further investigation it seems that it's only super slow if there are no `# BEGIN` OR `# END` matches in the file. (It takes only 1 second if the delimiters from the student version of the project are in the file. The 12 second number was from running the staff solution.)

**Comment by papajohn** [comment]
@qiaojianjack it would be nice if finding snippets took no time rather than 1-12 seconds. A case-sensitive regex might be slightly faster. Just looping through lines instead of using a regex might be much faster.

**Comment by qiaojianjack** [comment]
I didn't remember getting such a long running time from either my machine or Albert's during the summer, but I will definitely investigate into it. Actually the looping-through-file solution was slower than the regex at that time, so it might be a regex problem.

**Comment by Sumukh** [comment]
We decided to remove the regex search of code so we can avoid the delay from the regex. If the snippets are important for analytics purposes, they can be run after the fact. There will still be an approximate measure for what a student is working on through the log file that was added in #169
