### ISSUE TITLE
Support prompts with no code

### ISSUE THREAD

**Issue by brianhou** [Cal-CS-61A-Staff/ok-client#122]
```
>>> import hog
>>> hog.four_sided = hog.make_test_dice(1)
>>> hog.six_sided = hog.make_test_dice(3)
>>> always = hog.always_roll
>>> 
>>> # Play function stops at goal
>>> s0, s1 = hog.play(always(5), always(3), score0=91, score1=10)
```

An empty line can be useful to show where the setup code ends and the test code begins. However, the client currently requires that there is a space after the prompt `>>>`. If the trailing space disappears, then a SyntaxError may appear (depending on the lines before the prompt) or the client will expect the string '>>>' as output from the previous line. Atom silently strips trailing whitespace, so when students open a test file with an empty prompt, it starts to break.

What would the consequences be if we allowed `>>>` to be a prompt, rather than just `>>>\s+` or whatever the current prompt is?

**Comment by albert12132** [comment]
I'd have to take a closer look at the code, but the first thing that comes
to mind is that indented suites (like the body of a while loop) would be
stepped off leading whitespace. I think I've tried >>>\s* before, and it
ran into that problem.
