### ISSUE TITLE
1.4.2 deployed incorrectly

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok-client#124]
v1.4.2 isn't here: https://pypi.python.org/simple/okpy/

As a result, installation fails for me:

```
pip install -r ../requirements.txt
Downloading/unpacking okpy==v1.4.2 (from -r ../requirements.txt (line 1))
  Could not find a version that satisfies the requirement okpy==v1.4.2 (from -r ../requirements.txt (line 1)) (from versions: 1.0.10.dev1, 1.0.10.dev2, 1.0.10, 1.0.11, 1.0.12, 1.0.6, 1.0.7.dev1, 1.0.7.dev2, 1.0.7.dev3, 1.0.7.dev4, 1.0.7, 1.0.8, 1.0.9.dev1, 1.0.9, 1.1.0, 1.1.2, 1.3.23, 1.4.2, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.5, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.5, v1.2.6, v1.2.7, v1.2.8, v1.2.9, v1.3.0, v1.3.1, v1.3.10, v1.3.11, v1.3.12, v1.3.13, v1.3.14, v1.3.15, v1.3.16, v1.3.17, v1.3.18, v1.3.19, v1.3.2, v1.3.20, v1.3.21, v1.3.22, v1.3.24, v1.3.25, v1.3.26, v1.3.27, v1.3.28, v1.3.29, v1.3.3, v1.3.30, v1.3.31, v1.3.32, v1.3.33, v1.3.34, v1.3.35, v1.3.36, v1.3.4, v1.3.5.dev1, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.4.0, v1.4.1)
Cleaning up...
No distributions matching the version for okpy==v1.4.2 (from -r ../requirements.txt (line 1))
Storing debug log for failure in /Users/denero/.pip/pip.log
make: *** [../published/ok] Error 1
```

**Comment by brianhou** [comment]
I think the right thing to do is to change requirements.txt back to 1.4.1. We added a feature last night to help with autograding, but we were worried about releasing the update while students are working on Hog.

**Comment by brianhou** [comment]
The requirements.txt should be fixed now. Sorry!

**Comment by Sumukh** [comment]
https://pypi.python.org/pypi/okpy seems to list 1.4.2 

-- 
Sumukh Sridhara

On September 9, 2015 at 11:02:21 AM, Brian Hou (notifications@github.com) wrote:

I think the right thing to do is to change requirements.txt back to 1.4.1. We added a feature last night to help with autograding, but we were worried about releasing the update while students are working on Hog.

**Comment by Sumukh** [comment]
I missed a step - the release has to be unhidden from the PyPi dashboard. For now we should just rollback the requirement (which Brian did) and only release when it’s ready. 

-- 
Sumukh Sridhara

On September 9, 2015 at 11:03:46 AM, Sumukh Sridhara (sumukh1@gmail.com) wrote:

https://pypi.python.org/pypi/okpy seems to list 1.4.2 

-- 
Sumukh Sridhara

On September 9, 2015 at 11:02:21 AM, Brian Hou (notifications@github.com) wrote:

I think the right thing to do is to change requirements.txt back to 1.4.1. We added a feature last night to help with autograding, but we were worried about releasing the update while students are working on Hog.
