### ISSUE TITLE
Doctests from imported functions are also run (when running `python3 ok`)

### ISSUE THREAD

**Issue by brianhou** [Cal-CS-61A-Staff/ok-client#128]
The culprit seems to be `sources/doctests/__init__._load_tests`. It should probably check that `name` is defined in `module`.

**Comment by albert12132** [comment]
Can you be more specific? https://github.com/Cal-CS-61A-Staff/ok-client/pull/102 sort of takes care of this. If you run OK without specifying any questions, OK will use the `default_tests` listed in the `.ok` config file.

**Comment by brianhou** [comment]
I think it's possible to fix this even without #102; it just seemed like we stumbled on unexpected behavior.

In the lab05 zip that was originally released ([lab05.zip](https://github.com/Cal-CS-61A-Staff/61a-fa15-website/blob/66c40c2838a85bfc1d0e97f4068488f904016d48/lab/lab05/lab05.zip)), we forgot to specify that we only wanted to doctest `lab05_extra.py:info` rather than all of `lab05_extra.py`.

Since `lab05_extra.py` imports all of `lab05.py` (which has functions without doctests) running `python3 ok` meant that `ok` was looking for doctests for all functions in `lab05.py` and `lab05_extra.py`. I think preferred behavior would be that `ok` only looks for doctests for functions that were defined in `lab05_extra.py`, rather than any function in `dir(lab05_extra)`. This would match up with the behavior of the doctest module.
