### ISSUE TITLE
Support for IPython notebooks

### ISSUE THREAD

**Issue by SamLau95** [Cal-CS-61A-Staff/ok-client#135]
We're using the ok client for all programming assignments for
[DS8](http://data8.org/) and it's quite a challenge to work with.

Our current workflow when a student clicks the "Run ok tests" button in the
JupyterHub interface is:

1. Export the IPython notebook as a `.py` file.
2. Remove the `get_ipython` lines in the resulting file.
3. Find all the cells that start with `# ok` and run them. The contents of these
   cells call the `ok` client to run the corresponding tests.

This is less than ideal for the following reasons:

- The `ok` cells in the notebook can't actually be run directly since the
  notebook won't be exported. More confusingly, the `ok` script will be run on
  old code from the last time the code was exported. This means that the ok
  tests can't be run locally if the ok-extension isn't installed.
- The `ok` script needs to run the entire notebook before being able to run
  tests which is often slow (conceptually, each `ok` cell is testing one filled-
  in student cell). This often results in the case where a student is partway
  finished with a notebook and runs the `ok` tests only to have them fail
  because of a later cell.
- As a corollary, the `ok` script only reads in the final values of student
  variables. This is not a huge issue but it causes confusion.

I think these issues can be resolved if the `ok` client is able to look at cells
in the notebook specifically. I'm not sure how involved this is, so any feedback
would be appreciated.

**Comment by Sumukh** [comment]
I'm not sure how DS8 uses JupyterHub and ok - but there seems to be a way to autograde assignments programmatically (in addition to other grading tools for JupyterHub) 

this could be extension forked off nbgrader 

https://github.com/jupyter/nbgrader/blob/master/nbgrader/apps/autogradeapp.py

Is the challenge here being able to run ok tests both on jupyterhub as well as locally? 

> The ok script needs to run the entire notebook before being able to run tests which is often slow  
This might be alleviated by different test design (I'm not sure how tests are written currently). 

It is true that that a syntax error later in the file may cause issues and prevent ok from loading the file. 
Perhaps the file export can chop off the file after the question (or maybe most recently run cell?).

> As a corollary, the ok script only reads in the final values of student variables. This is not a huge issue but it causes confusion.
Again test design should be to solve this? 

Another Idea:
What if ok was summonable from python? as in students would just type (or the button would call) 
`ok.grade(5)` 
and the ok tests would run in the current environment?

**Comment by papajohn** [comment]
I think the best solution is to doctor the exported .py file so that it
only contains a subset of the original notebook contents. The same flow we
have now would be preserved, but the problems would go away.

Running in the current environment is also a great idea if we can figure
out how to set it up.

**Comment by SamLau95** [comment]
@Sumukh How involved would implementing the functionality to call `ok` from Python be? I'd be happy to work on it if its reasonable.

**Comment by Sumukh** [comment]
I'm not sure. I haven't used the DS8 setup. 

It could be as simple as: 
ok-integration.py 
```
import os 
def grade(qNum, config="lab.ok"):
  # export to notebook py file 
  os.exec("python3 ok --config " + config + " -q " + qNum) 
```
iPython Notebook import 
``` 
import ok-integration as ok
```

**Comment by Sumukh** [comment]
@SamLau95 
It looks pretty easy if you bundle the ok-client source code: 

```
$ git clone https://github.com/Cal-CS-61A-Staff/ok-client.git okclient
$  python3
Python 3.4.3 (default, Aug 11 2015, 08:57:25)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import okclient
>>> from okclient.client.cli import ok
>>> ok.main()
=====================================================================
Assignment: Project 4: A Scheme interpreter
OK, version v1.4.7
=====================================================================

Running tests

---------------------------------------------------------------------
Question 20 > Suite 1 > Case 2

....

OK is up to date
```

**Comment by papajohn** [comment]
You can definitely import source from the ok application just by adding it
to the pythonpath.

Running ok from the ipython environment would be a big win, given how long
it takes to load datasets for the course. Thanks for taking a look, Sam.
albert12132 knows the client codebase very well if you need guidance.

**Comment by SamLau95** [comment]
@Sumukh Ah, that's really cool. Thanks for looking into this for us! When you call `ok.main()` there, does that run in the current environment? That is, if I wrote

```
>>> foo = 2
>>> ok.main()
```

Would the ok tests have access to `foo`? It looks like it's loading the config file for Project 4 and subsequently importing a python file.

If the ok tests do in fact run in the current environment then it seems like I can avoid importing the student submission in the tests entirely and just call `ok` using what's currently defined. Does that sound right to you?

**Comment by albert12132** [comment]
@SamLau95 OK doesn't run in the current environment; every test starts with a clean environment. So in the example you give, OK tests would not have access to `foo`.

I'm not familiar with DS8's assignment/test structure, so correct me if I'm wrong. It sounds like you want to be able to call `ok` programmatically from within each test (i.e. in your test, you perform whatever setup the test needs, then you call OK to check the student solution). That isn't supported, and *could* be implemented, but would require few nontrivial changes to the ok-client codebase.

Can you point me to a sample DS8 assignment that I can test? I have no experience with iPython notebooks so I'm having a hard time understanding the problems listed your initial post.

**Comment by papajohn** [comment]
The problem is equivalent to running an OK test from within an interactive
session. E.g.

>>> x = load_data_for_five_minutes()
>>> y = <some expression the student writes>
>>> ok.test('q1') # Executes test cases that reference y and uploads results

The goal is to have students modify their expression and then re-execute
the ok test without ever having to re-load x.

**Comment by albert12132** [comment]
Where is the test 'q1' coming from (e.g. a file)? In this example, is the desired behavior supposed to reset the test's state (except for the data loaded in x) every time ok.test is called? One workaround is to have a separate python module that loads your data, then import that python module in the OK tests (this is kind of hacky because it relies on the fact that Python only imports modules once, but 61A uses it in at least the Maps project).

In any case, OK doesn't support this use case. ok-client was originally designed with the assumption that each invocation would make a single pass through the protocols. As a result, there's no API for programmatically interacting with individual tests multiple times in a single session. Fully providing this sort of support would probably require a sizable redesign of OK.

**Comment by SamLau95** [comment]
@albert12132 Gotcha, thanks for the info.
@papajohn Given this, is there a reason to use the `ok` grader instead of something like https://github.com/jupyter/nbgrader ?

**Comment by papajohn** [comment]
`q1` would be loaded in the same manner as a standard ok test: find a .ok
file, load a tests/q1.py file full of tests, and execute the tests. The
only difference is that we wouldn't start from a fresh environment when
executing a test.

ok has a lot of advantages — let's get it working.

**Comment by albert12132** [comment]
Still trying to understand the workflow. Does this sound correct:

1. Begin an OK session (i.e. run ok on the command line)
2. Load q1.py, including datasets
3. Run the q1 test.
4. Without quitting the current OK session, the student has the opportunity to change their code
5. Run the q1 test again.
6. Repeat step 4 and 5 as necessary.
7. Exit the current OK session.

**Comment by papajohn** [comment]
Not quite.

1. Start an interactive Python session and modify the environment by
executing various statements
2. Import ok module into the interactive session
3. Load contents of q1.py into the current environment and run its tests by
evaluating a Python expression (such as ok.grade('q1'))
4. Student can further modify the environment
5. Re-execute tests when ok.grade('q1') is evaluated again
6. Repeat steps 4 & 5 as necessary

The interactive session exits whenever the student ends it.

**Comment by albert12132** [comment]
Got it. How early would you need support for running OK in a Python session (e.g. the ok.grade function)? To do it right, I'd need to revisit the design of ok-client, and might take a month or two, depending on how much time I have. If you need it soon, we can try to work out a quick (not so robust) way to do this.

**Comment by papajohn** [comment]
Jan 15.

**Comment by albert12132** [comment]
I started a short design doc [here](https://docs.google.com/document/d/16_7CHwjObKQNt0vR51E877e1lv00AbviFOec-i-ipWw/edit?usp=sharing). Let me know if it suits your use case.

**Comment by papajohn** [comment]
Looks perfect. The only issue is that protecting the global environment
completely is hard, and I don't think we should go out of our way to do so.
For example, I don't think we should `deepcopy` everything (which could be
slow); just pass a shallow copy of globals to the test.

**Comment by SamLau95** [comment]
This looks great! Thanks a bunch.

Agree on the point about shallow copying. Tests shouldn't cause
side-effects.

**Comment by albert12132** [comment]
Ran into an issue: `globals()` returns the dictionary of global variables in the current module. The intended API is defined in a module called `client.cli.api.assignment`, which does roughly the following:

```python
class Assignment:
    def grade(self, *questions, env=None):
        if env is None:
            env = globals()
        # call grading utilities with env
```

`globals()` will be scoped to `client.cli.api.assignment`, not `__main__` (i.e. the student's environment). The only way around this (that I can think of) is for API users to pass `globals()` explicitly:

```python
assignment = load_assignment(config_path)
assignment.grade('q1', globals())   # Can't use the default env anymore.
```

Are you okay with that?

**Comment by albert12132** [comment]
@brianhou suggested

```python
import __main__

env = dir(__main__)
```

I'll go with that.

**Comment by papajohn** [comment]
Fancy!

**Comment by albert12132** [comment]
@papajohn @SamLau95 do you need the `Assignment.backup` feature? If not, I'll leave it out for now. If you do, what information are you expecting to backup?

**Comment by papajohn** [comment]
We do not need backup or submit. Submission will be run in the standard
file-oriented way.

**Comment by papajohn** [comment]
Works great! LGTM. I'll let you merge b/c I've lost track of how versions are incremented in this project.

**Comment by albert12132** [comment]
@brianhou any comments before I merge?
