### ISSUE TITLE
Cannot load OK test for files that end in A.py or B.py

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok-client#142]
I have one student who is working on the Scheme project self-paced. Every time he tries to run a test that ends in A.py, such as 05A.py, he gets the error "Cannot load OK test [filename]". Has anyone seen this problem? Python 3.5 on Mac installed with homebrew.

The student: @nikhilunni

**Comment by nikhilunni** [comment]
Also, the same for all the *B.py tests.

**Comment by Sumukh** [comment]
@nikhilunni I just want to make sure that file exists. What's the output of `ls -al tests` 

If `05A.py` exists - can you also do `cat tests/05*` ?

**Comment by papajohn** [comment]
I checked that the file does have contents — I didn't notice anything weird. @nikhilunni , if you could paste the whole file into a comment, we could take a closer look.

**Comment by nikhilunni** [comment]
I'm running with OK version 1.4.9. 
I got the tests and all the files from [here.](http://inst.eecs.berkeley.edu/~cs61a/sp15/proj/scheme/scheme.zip)

Here's the output of 05A.py:
"test = {
  'name': 'Question 5',
  'partner': 0,
  'points': 1,
  'suites': [
    {
      'cases': [
        {
          'answer': 'b8204d82bf3c1d4f24f6eca40b70a622',
          'choices': [
            r"""
            Pair(A, Pair(B, nil)), where:
                A is the symbol being bound,
                B is an expression whose value should be bound to A
            """,
            r"""
            Pair(A, Pair(B, nil)), where:
                A is the symbol being bound,
                B is the value that should be bound to A
            """,
            r"""
            Pair(A, B), where:
                A is the symbol being bound,
                B is the value that should be bound to A
            """,
            r"""
            Pair(A, B), where:
                A is the symbol being bound,
                B is an expression whose value should be bound to A
            """,
            r"""
            Pair('define', Pair(A, Pair(B, nil))), where:
                A is the symbol being bound,
                B is an expression whose value should be bound to A
            """
          ],
          'hidden': False,
          'locked': True,
          'question': 'What is the structure of the expressions argument to do_define_form?'
        },
        {
          'answer': 'a48fa38f68497d2e422dd31c397eaf76',
          'choices': [
            'make_call_frame',
            'define',
            'lookup',
            'bindings'
          ],
          'hidden': False,
          'locked': True,
          'question': r"""
          What method of a Frame instance will bind
          a value to a symbol in that frame?
          """
        }
      ],
      'scored': False,
      'type': 'concept'
    },
    {
      'cases': [
        {
          'code': r"""
          scm> (define size 2)
          3cef6153a5a93752178b1028ce91fc84
          # locked
          scm> size
          9ea224e62b219a1ee61849f282da5e65
          # locked
          """,
          'hidden': False,
          'locked': True
        },
        {
          'code': r"""
          scm> (define x (+ 2 3))
          57775d5ff999af0ee4cbfa3aa0507be8
          # locked
          scm> x
          020ab0752ad7f917c8c0e4ac6c80edf7
          # locked
          scm> (define x (+ 2 7))
          57775d5ff999af0ee4cbfa3aa0507be8
          # locked
          scm> x
          a7d60ae9b0b81fce195ed5b13796867a
          # locked
          scm> (eval (define tau 6.28))
          425e5e1cf58a1ce2072411c7c0f91257
          # locked
          """,
          'hidden': False,
          'locked': True
        },
        {
          'code': r"""
          scm> (define pi 3.14159)
          pi
          scm> (define radius 10)
          radius
          scm> (define area (* pi (* radius radius)))
          area
          scm> area
          314.159
          scm> (define 0 1)
          SchemeError
          """,
          'hidden': False,
          'locked': False
        }
      ],
      'scored': True,
      'setup': '',
      'teardown': '',
      'type': 'scheme'
    }
  ]
}"

**Comment by Sumukh** [comment]
Thanks. This is occurring because we changed the partner field of tests (`A` or `B`) to be strings instead of integers as they were in SP15

@nikhilunni There are a variety of ways to fix this. One way is to go through all of the A/B tests and delete the line `'partner': 0,` or `'partner': 1,` from each one - this seemed to work for me. 

One other approach that's a bit easier is to use the [ok version](http://inst.eecs.berkeley.edu/~cs61a/sp15/proj/scheme/ok) from the sp15 and use the `--local` flag with ok to prevent updating. I'd recommend doing the latter. 



Relevant debug output: 
```
INFO  | assignment.py:99 | Loaded tests/04.py
WARNING  | ok.py:129 | Assignment could not load
Traceback (most recent call last):
  File "ok/client/sources/ok_test/__init__.py", line 47, in load
    assign.cmd_args.timeout, **test)}
  File "ok/client/sources/common/core.py", line 177, in __call__
    setattr(obj, attr, value)
  File "ok/client/sources/common/core.py", line 199, in __setattr__
    value = field.coerce(value)
  File "ok/client/sources/common/core.py", line 47, in coerce
    'type {}'.format(value, self.__class__.__name__))
client.exceptions.SerializeException: 0 is not a valid value for type String

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ok/client/cli/ok.py", line 113, in main
    assign.load()
  File "ok/client/cli/common/assignment.py", line 75, in load
    self._load_tests()
  File "ok/client/cli/common/assignment.py", line 98, in _load_tests
    self.test_map.update(module.load(file, parameter, self))
  File "ok/client/sources/ok_test/__init__.py", line 49, in load
    raise ex.LoadingException('Cannot load OK test {}'.format(file))
client.exceptions.LoadingException: Cannot load OK test tests/05A.py
Error loading assignment: Cannot load OK test tests/05A.py
Checking for software updates...
INFO  | software_update.py:19 | Existing OK version: v1.4.9
```
