### ISSUE TITLE
Allow API to execute locked tests

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok-client#155]
When executing a locked test using the `grade` method, the computed result of evaluation should be hashed, and the hash of the result compared to the locked hash. In this way, a locked test can be used for correctness-checking while remaining locked.

If the test fails, the input to the test should be displayed, but the comparison of hashed values should be suppressed (because it would be confusing).

I think we'll need this functionality to launch our first Data 8 project in ~10 days. Can anyone help out?

**Comment by jathak** [comment]
Should the API always execute locked tests or should there be some flag to the `grade` method to allow it?

**Comment by jathak** [comment]
Also, does this need to be added for every type of test suite or just certain ones?
