### ISSUE TITLE
Store authentication token in persistent config directory

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok-client#157]
Instead of storing the authentication token in an `.ok_refresh` file for each application, it should be stored in some central location so the user only has to authenticate once.

**Comment by jathak** [comment]
Could this be done by just saving the auth token to `~/.ok_refresh` or `~/.ok_config/ok_refresh`? Would there ever be a case where a student needs to be logged into different accounts for different classes?

**Comment by Sumukh** [comment]
Yes. I prefer the folder approach because we may want to store a few more files in the near future. 

For the case you mention, the student can "logout" and relogin with `python3 ok --auth`. I don't think we have to worry too much about this.

**Comment by knrafto** [comment]
I second making a config folder. On Unix the config folder should be at `~/.config/ok/` (or maybe `~/.config/okpy/`), and on Windows Vista or greater it would be `C:\Users\<username>\AppData\Local\ok\`
