### ISSUE TITLE
Reload tests after edit

### ISSUE THREAD

**Issue by peterasujan** [Cal-CS-61A-Staff/ok-client#160]
Calling `load_assignment` after editing a test file doesn't pull in the changes to that file unless I completely restart Python. Is there a way to force `load_assignment` to re-read all the test files?

**Comment by brianhou** [comment]
It might work to add `importlib.reload(module)` after the `importlib.import_module` in `client/api/assignment.py`, if someone wants to investigate.

**Comment by brianhou** [comment]
@peterasujan, try using this binary: [ok.zip](https://github.com/Cal-CS-61A-Staff/ok-client/files/122722/ok.zip)

**Comment by peterasujan** [comment]
Nice, that fixed it!

**Comment by brianhou** [comment]
Closed, see #161.
