### ISSUE TITLE
Users should be able to backup and submit with syntax errors

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok-client#170]
When there's a syntax error OK still checks for software updates, but it won't try to back up or submit the assignment.
```
$ python3 ok
=====================================================================
Assignment: Homework 5
OK, version v1.5.4
=====================================================================

Traceback (most recent call last):
  File "hw05.py", line 1
    '# Linked List Class
                       ^
SyntaxError: EOL while scanning string literal

Error loading assignment: Error importing file hw05.py
Checking for software updates...
OK is up to date
```

**Comment by Sumukh** [comment]
While we're on the topic of Syntax Errors - could we add a message that makes it clear that it's not an error with OK and that to resolve the error the user should edit the file around Line X

```
SyntaxError .... 
Error Loading Assignment: Syntax Error -  Inspect the area around line Y in ____.py for a syntax error 
```

**Comment by Sumukh** [comment]
That being said, it's somewhat of a feature that we don't let students submit with syntax errors - this avoids a lot of syntax errors when grading. 

Letting students backup with syntax errors sounds fine though. It be nice if we annotate somewhere in the messages that there was a syntax error (for analytics purposes)
