### ISSUE TITLE
Add Logic OK tests

### ISSUE THREAD

**Issue by brianhou** [Cal-CS-61A-Staff/ok-client#175]
We're planning to teach Logic this summer, and it'd be great if students could check their solutions.

It seems like the best way to do this is to adapt `client/sources/ok_test/scheme.py` and implement `LogicConsole` and `LogicSuite`. @albert12132, if that sounds reasonable, I'll take a shot sometime this week.

**Comment by albert12132** [comment]
Sure. You can also make them non-OK tests (like in `client/sources/scheme_test/`), which should use the same mechanism as the scheme tests.

**Comment by knrafto** [comment]
Added in #192
