### ISSUE TITLE
In interactive mode (-i flag), Ctrl-D does not quit interactive console.

### ISSUE THREAD

**Issue by brianhou** [Cal-CS-61A-Staff/ok-client#18]
Not sure if this was a design choice or not.

**Comment by albert12132** [comment]
I'm not able to replicate this issue, but I think what you're seeing is this: every time you type Ctrl-D, it exits the current interactive prompt, but it opens up another one immediately for the next unsuccessful test.

I'll take a look at a fix.

**Comment by brianhou** [comment]
Oops, I think you're right -- I wasn't paying that much attention.

**Comment by albert12132** [comment]
What do you think expected behavior should be? If they exit an interactive
interpreter, should it just abort all tests? I didn't expect students to
use -i without specifying a question, but as you saw, it can be confusing
to have to quit out of multiple interactive consoles.
