### ISSUE TITLE
Authentication not working

### ISSUE THREAD

**Issue by Some3141** [Cal-CS-61A-Staff/ok-client#20]
https://piazza.com/class/i4q8ow8g8bv7oa?cid=167

**Comment by albert12132** [comment]
I'm unfamiliar with the code that sends requests to the server. @Some3141 or @sharadmv might have a better idea of what's going on.

**Comment by Some3141** [comment]
It doesn't send anything to the server- it just uses Google OAuth to authenticate the students. I can take a look at it when I get a chance, but that probably won't be until tomorrow.

**Comment by albert12132** [comment]
Has this been resolved with #40 ?

**Comment by Some3141** [comment]
Yes

On Tuesday, February 3, 2015, albert12132 <notifications@github.com> wrote:

> Has this been resolved with #40
> <https://github.com/Cal-CS-61A-Staff/ok-client/pull/40> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Cal-CS-61A-Staff/ok-client/issues/20#issuecomment-72718232>
> .
>


-- 
Sent from Phone
