### ISSUE TITLE
After authentication, don't attempt to serve homepage from client

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok-client#203]
It looks like v2, and isn't accurate. Instead:
- Tell the user to close the tab
- Redirect to the real OK

I vote for just telling them to close the tab, since that's what most do anyway.

**Comment by Sumukh** [comment]
> Not accurate
AFAIK it was updated to use the right API call. Which part is not accurate? 

Having the post login success page show what email/courses is very useful to make sure people are using the right account.  https://github.com/Cal-CS-61A-Staff/ok-client/pull/76

Having it redirect to the Ok homepage is probably insufficient (and also would require another login). 

I'm okay with a redirect to a specific page on the OK server that flashes an error if you aren't enrolled (the access token would have to be a URL parameter to avoid the extra login)

Another option is to print out the enrollment info in the terminal. I'm okay with this if we can bring focus back to the terminal after authentication.

**Comment by knrafto** [comment]
Oh, it looked like v2 in @DavidHarrison 's screenshot. Haven't checked myself.

Switching ok-client to use OK's newfangled OAuth should mean they'll automatically sign in with the same email they signed in to ok-server with, right?

We could also redirect to the course page, which should flash an error if they're not enrolled.

**Comment by Sumukh** [comment]
Redirect to the course page when the client uses OK OAuth sounds good. 

The design for that page is still V2 like (but it hits the right V3 endpoint) - I don't think it's worth it to change this page if we're just going to redirect when we switch out the auth system. 

I can fix the css issue mentioned earlier (https://github.com/Cal-CS-61A-Staff/ok/issues/797)  in the meantime

**Comment by knrafto** [comment]
Resolved by #256
