### ISSUE TITLE
Do we need both protocol.on_start and protocol.on_interact now?

### ISSUE THREAD

**Issue by albert12132** [Cal-CS-61A-Staff/ok-client#21]
I recall that the original intention of having on_start is to send some info to the server before running on_interact. Now that protocol.on_start and protocol.on_interact are simply run sequentially, one after the other, are the two still necessary? I should note that no protocol currently implements both on_start and on_interact.

**Comment by Some3141** [comment]
We don't. I'll remove it when I get a chance.

**Comment by albert12132** [comment]
Related to #7
