### ISSUE TITLE
OK unlocking should not eval

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok-client#211]
I've seen several students type `5/2` as an answer to a `print(5/2)` WWPD, even though this is not the correct answer.

Instead, we could try to parse and match the syntax trees, or something similar, to handle cases like
`[1,2,3] ~ [1, 2, 3]`

**Comment by knrafto** [comment]
See #59 for the original issue.

**Comment by Sumukh** [comment]
IMO: `ast.literal_eval()` seems like the right solution here. We attempt to `literal_eval` the student response, if it fails the client fallbacks to do a normal comparison. 

> The string or node provided may only consist of the following Python literal structures: strings, numbers, tuples, lists, dicts, booleans, and None.
