### ISSUE TITLE
OK authentication should be simpler (Browserless Auth) 

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok-client#212]
Many students have issues launching their browser or redirecting back to localhost. Instead our OAuth flow show be simpler:
- OK prints a link and says "open this link in your browser to sign in"
- After login, the webpage should say "copy this code back into your terminal"

This would solve many of our OK login issues.

**Comment by Sumukh** [comment]
I agree that it's a good fallback. (gcloud auth does this when it can't open a browser) 

> This would solve many of our OK login issues.
Would it? I'm not convinced that it would. 

Also it's worth considering that many students find it hard (or at least not obvious) for people on windows to copy things from their terminal

**Comment by knrafto** [comment]
> Would it? I'm not convinced that it would.

I think so. I've seen a couple windows that couldn't redirect to 127.0.0.1 because of firewall or what-have-you. And there was an issue today in lab where the lab machines couldn't open a browser.

Maybe we could leave a note to highlight and right-click to copy. That works on most terminals, right?
