### ISSUE TITLE
--unlock should only run default_tests

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok-client#214]
Right now it runs every test. Also, when submitting, only complain about when the non-optional questions haven't been unlocked, instead of all of them.

**Comment by colinschoen** [comment]
I'm half convinced this functionality already exists when `default_tests` is specified. 

https://berkeley.box.com/v/Ok-package

When running `python3 ok --unlock` only the `default_tests` unlock tests are run even though `q1` has a locked test.

**Comment by knrafto** [comment]
Alright I'm convinced too. Thanks for investigating Colin. We should probably add a test, but for now I'll just close the issue
