### ISSUE TITLE
Easy way to relock tests (for students)

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok-client#219]
Students often ask to relock a test suite and try again. We should let them. The current `python3 ok --lock` command doesn't seem to quite work as intended. 

The reason it does nothing for most assignments is because the lock protocol isn't run.

**Comment by Sumukh** [comment]
Instead of actually changing the file, we could change the way that unlock.py works to not ignore already answered questions when run with `--lock`

**Comment by knrafto** [comment]
Depends on #247

**Comment by Sumukh** [comment]
What does the ideal invocation for this look like? 

`ok --lock -q Foo --case 1`  (because the question/case is specified the locking protocol will lock any questions that have already been answered) 

(or we could add a `--relock`)

**Comment by epai** [comment]
This was resolved with #278

**Comment by Sumukh** [comment]
Is #278 the right pr here?

**Comment by epai** [comment]
I think so?  I may be wrong, but I thought the reason why `ok --lock` wasn't working was because the locking protocol wasn't being reliably run.  But with #278, all protocols are always loaded, so it should work now
