### ISSUE TITLE
Provide a way for students to run a single test

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok-client#224]
e.g. `python3 ok -q 05 --suite 4 --test 3`

this has been requested several times, so it would be nice to have for the maps project.

**Comment by jalagar** [comment]
Yea I think having ok took a big part of debugging out of the student's hands as now they just post their ok output and don't even attempt to add print statements as it ruins previous tests. They can always use -v to test all the tests but I think really emphasizing debugging skills will help students become self sufficient

**Comment by Sumukh** [comment]
+1. 

We can't really recommend running `python3 ok -q 05 -i` (though it can be useful) because that only works when your print statements don't mess up an earlier test.

**Comment by knrafto** [comment]
Closed by #235
