### ISSUE TITLE
Log IP and Hostname

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok-client#225]
I'd like to add this to the Analytics Protocol. If we collect this information it would have to be censored for any anonymized exports. 

```
import socket

hostname = socket.gethostname()
IP = socket.gethostbyname(hostname)
```

**Comment by knrafto** [comment]
Why does it matter what the user's hostname is? And the IP you get will be a local IP, and not very useful.

**Comment by colinschoen** [comment]
You would have to make an HTTP request to fetch the WAN IP.

**Comment by Sumukh** [comment]
Yeah - I think this isn't worth it at the moment. If we come up with a compelling reason for this we can look into doing that.
