### ISSUE TITLE
--submit cannot connect to internet

### ISSUE THREAD

**Issue by dicksontsai** [Cal-CS-61A-Staff/ok-client#24]
Here's what I get when I try to run `python3 ok --submit`
    Backing up your work...
    Submitting project... 0% complete
    Submitting project... 0% complete
    Submitting project... 0% complete
    Submitting project... 0% complete
    Submitting project... 0% complete
    Submission failed. Please check your network connection and try again

However, I can still browse other web pages from my computer. All other ok commands seem to work as well (I was able to authenticate).

My computer runs on OSX Yosemite.

**Comment by Some3141** [comment]
Can you try it again? It might have been updating.

**Comment by papajohn** [comment]
Please try again — we just deployed again.

**Comment by dicksontsai** [comment]
Works at home! I'll test tomorrow on AirBears, but I'll close this issue for now.
