### ISSUE TITLE
Incorrect URL displayed after submission

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok-client#25]
When I submitted lab 2, the URL displayed in the client (after submission finished) did not contain any file contents. 

I believe the client submits multiple times, and it should only show the URL for the submission that actually includes the contents of the files.

**Comment by papajohn** [comment]
I just experienced this bug again when submitting Hog. 

Link displayed by OK client was:
https://ok-server.appspot.com/#/5165212546105344/submission/6207592653127680

Actual link for my submission was:
https://ok-server.appspot.com/#/5165212546105344/submission/6512093754818560

**Comment by albert12132** [comment]
Is this still an issue?

**Comment by Some3141** [comment]
Don't think so. We'll close it.
