### ISSUE TITLE
Collect justification for unlocking questions

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok-client#260]
Related to @ksteph's work. 

Involves:
- Small changes to the unlocking hints code to prompt students if the answer is one of a few recognized ones. 
- Sometimes ask students for justification even if it's correct 
- Handle different treatment groups

**Comment by knrafto** [comment]
Sounds like we need a generic way to A/B test

**Comment by ksteph** [comment]
@knrafto 
Considering I need this for this semester, I doubt A/B testing will be done in time. But perhaps this would be a good case study on how A/B testing would need to be implemented for this to be straightforward?

**Comment by knrafto** [comment]
Well we already have a server set up to assign treatment groups for unlocking guidance. I'm thinking we could factor that out and reuse it instead of making a whole new system.

**Comment by ksteph** [comment]
Ah, agreed about the treatment assignment server. Less clear about how to change OK or the OK server stuff to do A/B testing.

**Comment by knrafto** [comment]
Closed in #267
