### ISSUE TITLE
Automate ok-client releases

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok-client#264]
Releasing ok-client is error-prone. This morning we had a serious issue where the 1.8.2 github release had the 1.8.1 binary.

We could automate the release process with a script that:
* Update the version in `__init__.py`
* Git tag and push
* Open $EDITOR to draft new GitHub release, which recent commits since last version tag as a start
* Upload release and binary to GitHub
* Upload release to pypi
* Use OK api to update ok-client version and download link
* Remind the deployer to update the `requirements.txt` file for other repos (e.g. berkeley-cs61a)

The biggest challenge will be than many of these step require web authentication.

**Comment by Sumukh** [comment]
I have `git-extras` on my computer and there's a git release command that auto generates releases with changelogs (with all the commits since the last release) - but it doesn't handle files. 

Something like: https://github.com/aktau/github-release might make it easier - but it requires users having go on their systems.

**Comment by Sumukh** [comment]
Do we really need to store our compiled builds on Github Releases? It's certainly a nice to have but storing it in google cloud bucket might be easier if we are writing a script.

**Comment by knrafto** [comment]
Actually I've already written the binary uploading to GitHub. I haven't tested it yet. Google cloud actually seems harder because we would have to have another access token for that, or gcloud installed

**Comment by knrafto** [comment]
Should this check if your are on master, and git pull first? I can't see why you would want to release from another branch

**Comment by Sumukh** [comment]
Yeah (I've pushed to pypi from other branches accidentally and then had to throw away that version number since we can't delete/edit pypi releases)

**Comment by knrafto** [comment]
We also need a GitHub token (from https://help.github.com/articles/creating-an-access-token-for-command-line-use/). Where (and in what format) should the user of this script store that token so we can find it easily?

**Comment by Sumukh** [comment]
An environment variable seems like a good choice

`$ GH_TOKEN=abcdef ./deploy-ok.sh` 

Alternatively a `.ghtoken` or similiar file is also an option (if it's added to the `.gitignore`)
