### ISSUE TITLE
Build wheels before sending to pypi

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok-client#276]
Suggestion from @yuvipanda: 
> Could you also upload wheels rather than just sdists? Since there's no binary stuff there it isn't that much of an improvement, but it'll be nice to have and fairly easy to do so

Just tried to build a wheel and things seemed to work just fine.

**Comment by knrafto** [comment]
Is this simply running `python setup.py bdist_wheel` before `python setup.py sdist upload`?

**Comment by Sumukh** [comment]
I think so.
