### ISSUE TITLE
Auth errors with multiple instances of ok

### ISSUE THREAD

**Issue by Some3141** [Cal-CS-61A-Staff/ok-client#28]
Since we use a single port number (7777), authentication will always error when students have multiple instances of ok running. This might happen when, say, auth is taking too long, so a student opens up a new tab and auths again.

Now, my question is that is this desirable, or should we allow one of the authentications to succeed? (by using a random port number). Also, if students happen to have another service running on 7777, then ok won't interfere, but I think this is much less likely.

**Comment by albert12132** [comment]
Based off of the confusion in the past few days, I don't think this is desirable behavior. Is there a reason why auth is taking so long in the first place?

**Comment by Sumukh** [comment]
Re: delay - It seems to be isolated to Airbears. My guess is that the lookup of localhost just takes a while on Airbears.

**Comment by Some3141** [comment]
Wait, the lookup of localhost has nothing to do with Airbears.

The auth would be taking so long mainly because the connection between their computer and Google's OAuth server is taking a while- we don't have any control over this at all.
