### ISSUE TITLE
Grading Protocol crashes when given non existent suite 

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok-client#302]
```
$ python3 ok -q 05 --suite 999

  File "ok/__main__.py", line 46, in <module>
  File "ok/client/cli/ok.py", line 202, in main
  File "ok/client/protocols/grading.py", line 37, in run
IndexError: list index out of range
```

**Comment by epai** [comment]
Some helpful tips:
- command line arguments are parsed in `client/cli/ok.py`
- suite info is stored in the appropriate test.  not all tests have a `suites` attribute, so you'll have to check using `hasattr`

A dead simple approach would be to just use a `try/except`.  I'll leave implementation details up to you.

**Comment by epai** [comment]
Awesome work @krbharathala!  Next time, instead of pushing directly to master, please make a pull request so we can review it first.
