### ISSUE TITLE
Potential issue with __pycache__

### ISSUE THREAD

**Issue by albert12132** [Cal-CS-61A-Staff/ok-client#31]
A student fixed an indentation problem in their code, but ok seemed to ignore those changes. Investigate further.

**Comment by Some3141** [comment]
How slow is it to run without __pycache__?

We can change "PYTHONDONTWRITEBYTECODE".

**Comment by albert12132** [comment]
Upon further inspection, I'm not able to reproduce the error. Python doesn't write *.pyc files for modules that can't load (e.g. IndentationErrors and SyntaxErrors). It might have been an unrelated issue.
