### ISSUE TITLE
Recursion Error in Auth

### ISSUE THREAD

**Issue by khalilsarwari** [Cal-CS-61A-Staff/ok-client#314]
After running OK, there appears to be some recursion error related to authentication. This can be temporarily resolved by reauthenticating as far as I can tell (`python3 ok --authenticate`)

![screen shot 2017-08-02 at 5 36 20 pm](https://user-images.githubusercontent.com/20780564/28900860-fa98b904-77a8-11e7-84d1-d8b96edb56cf.png)

**Comment by epai** [comment]
Fixed in #315
