### ISSUE TITLE
Show students what email they've submitted under & change wording for auth

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok-client#32]
I've seen a lot of students type in their ID Number instead of their CalNet username. Can we change the input prompt to ask for `CalNet Username:`? 

In addition, after submitting - it would be good for students to see what account it's submitted under. Something like 
```
Submission for test@example.com successful 
URL:  http://ok-server.appspot.com/#2323232/submission/123123
```

If the client doesn't easily have access to this information, we could also send the information down from the server.

**Comment by brianhou** [comment]
I'm a little surprised why this has suddenly become an issue; I don't think I heard about this happening at all last semester. It's also officially called a CalNet ID, so I don't know if changing it to CalNet Username would help? I agree it'd be useful for students to see which account it was submitted with, though.

**Comment by Sumukh** [comment]
Yeah, it's not actually that important - because if they do type in their id number they will still be taken to the right auth page.
