### ISSUE TITLE
"Submission Successful" after "Error Loading Assignment"

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok-client#33]
When there's an assignment load error, the client confusingly prints "submission successful".

![screen shot 2015-01-28 at 10 43 49 pm](https://cloud.githubusercontent.com/assets/320145/5970730/247f6aea-a7ec-11e4-9243-34b029376ed2.png)

**Comment by albert12132** [comment]
@Some3141 , we should change "Server submission successful" to something like "Backup completed."
