### ISSUE TITLE
ok should list all valid tests, perhaps when edit distance is too large

### ISSUE THREAD

**Issue by brianhou** [Cal-CS-61A-Staff/ok-client#4]
I think we should be more clear what problems ok is able to test. Using Homework 1 as an example, it is not clear that there are no tests for `if_function`.

Interestingly, running `python3 ok -q if_function` actually runs the tests for `hailstone`. I do think that running `python3 ok -q hailston` and running `hailstone` is nice, so maybe we should introduce some maximum edit distance we are willing to run a test for. Typing the entire function name out (as opposed to q1) is a bit inconvenient though, so I think somehow mapping `q1` to a list of functions to run doctests for would be preferable.

**Comment by Some3141** [comment]
Resolved by 6c9783c2cb444d200e6f217e3a5de4476d8426d8
