### ISSUE TITLE
Submit + Update should provide explanation for why the submission failed. 

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok-client#41]
Currently, if the client discovers it needs to update - the submission will fail - attempting to submit a few times before giving up. The submission will succeed on the second try. We should print should a different error message to make this clearer. (Something along the lines of 'ok had to update, please try submitting again')

```
Backing up your work...
Submitting project... 0% complete
Submitting project... 0% complete
Submitting project... 0% complete
Submitting project... 0% complete
Submitting project... 0% complete
Submission failed. Please check your network connection and try again
```

**Comment by albert12132** [comment]
This seems to be a (partial) duplicate of #68 .
