### ISSUE TITLE
RuntimeErrors are assumed to be maximum recursion depth exceeded

### ISSUE THREAD

**Issue by brianhou** [Cal-CS-61A-Staff/ok-client#47]
It seems to be a result of https://github.com/Cal-CS-61A-Staff/ok-client/blob/6f61f1e0d326fc31b872ec0ad5856131360074f8/client/sources/common/doctest_case.py#L225.

**Comment by brianhou** [comment]
It seems to be because of https://github.com/Cal-CS-61A-Staff/ok-client/blob/6f61f1e0d326fc31b872ec0ad5856131360074f8/client/sources/common/doctest_case.py#L225.

**Comment by albert12132** [comment]
I hardcoded that in there under the assumption the most common RuntimeError would be maximum recursion depth. Just wondering, what other runtime error did you see?

**Comment by papajohn** [comment]
The error, "Your final strategy should not call max_scoring_rolls" is
raised as a RuntimeError.
