### ISSUE TITLE
Empty doctest is considered a failed test

### ISSUE THREAD

**Issue by brianhou** [Cal-CS-61A-Staff/ok-client#51]
https://piazza.com/class/i4q8ow8g8bv7oa?cid=1167

If you define a helper function with no doctest, then we count that as a failure. I'm not sure if there's a good way to distinguish a student-defined helper function from a required function that they removed the doctests for.

**Comment by albert12132** [comment]
One way to avoid this is to list out the questions that should be tested explicitly in the *.ok file:

```
'hw3.py:square': 'doctest',
'hw3.py:double': 'doctest',
```

Another way is to simply ignore functions with no doctest. I'm not entirely sure this is desirable behavior, however, because if a student deletes the doctest, it will appear that there is no issue.

**Comment by brianhou** [comment]
I think explicitly listing it out might be better in the future. It's clunky, but it seems that there have been several Piazza posts about this.

**Comment by albert12132** [comment]
Another downside to this is that they can't use OK to doctest anything
that's not explicitly specified. They can always just use python -m doctest
for that, but it would be nice if OK were able to be the only thing they
need to run.

**Comment by brianhou** [comment]
I think what we discussed was explicitly listing out tests that will be graded. We would still provide a separate `--all` flag for the current functionality that gets all doctests and runs them.

**Comment by brianhou** [comment]
I think this was resolved?

**Comment by albert12132** [comment]
Most likely. Closing now.
