### ISSUE TITLE
Displaying Link Causes Confusion

### ISSUE THREAD

**Issue by Some3141** [Cal-CS-61A-Staff/ok-client#52]
We should display the backup link when students type in "python3 ok". It should only be displayed when --submit is shown.

**Comment by albert12132** [comment]
Do you mean we should *not* display the backup link when students don't use `--submit`?

**Comment by Some3141** [comment]
Yes.

**Comment by albert12132** [comment]
That sounds fine, but is this a frequent point of confusion?

**Comment by Some3141** [comment]
Yes- it's one of my most common complaints right now.
