### ISSUE TITLE
Integrate ucb.py with ok

### ISSUE THREAD

**Issue by albert12132** [Cal-CS-61A-Staff/ok-client#66]
The biggest issue with integration is usage. Ideally, the `__init__.py` file in OK can define an interface of features (like the `main` decorator, `interact`, and `trace`). However, Python doesn't support direct imports from ZIP-archives  (which is what OK is currently distributed as). For example, the following does not work:

```
from ok import main, interact, trace
```

The "easiest" way to work is to add `ok` to `sys.path`:

```
import sys
sys.path.insert(0, 'ok')
from ok import main, interact, trace
```

However, that solution is rather clunky. Thoughts on how to get around this?

**Comment by papajohn** [comment]
It's too bad there isn't a cleaner way, but that's not so terrible.

**Comment by albert12132** [comment]
After some discussion with @Sumukh and @brianhou , we decided not to integrate ucb.py with ok. If students wanted to use ucb.py functionality with `python3 hw1.py` instead of `python3 ok`, they would be required to use the import method described in my previous post--or they can modify PYTHONPATH. Neither are student-friendly.
