### ISSUE TITLE
Restoring from a backup

### ISSUE THREAD

**Issue by jathak** [Cal-CS-61A-Staff/ok-client#81]
Once I've finished #77, I'd like to add a `--restore` option that would allow students to retrieve a previous version of their assignment that's been backed up to the server. This could be particularly useful for partners on an assignment to share their work with each other.

I should be able to write this, but I'm not sure how I should handle overwriting existing files on the student's computer when replacing them with the backup. Here are the three ways I was thinking of handling this:

**Option A:** Warn the student that restoring to an older backup will overwrite the files currently on their computer and have them confirm that they want to do this.

**Option B:** Move the current version of any files that will be replaced into a subdirectory before replacing them.

**Option C:** Make a new server-side backup before restoring an old backup. This would probably be the most seamless option for students, but it would complicate assignment configurations by requiring that the restore protocol is listed after the backup protocol.

Let me know which if these options you think would work best or if you have some other idea.

**Comment by albert12132** [comment]
Option C shouldn't be too complicated. Also, we can consider something similar to option B:

**Option D**: Download the older backup into a subdirectory. It'll be up to the student to replace their files if they want. I suspect quite a few students might not want to completely replace their files and would instead copy and paste old code into their current file.

**Comment by soumyabasu** [comment]
I'm in favor of something with Option B and Option D- I don't really like the idea of ok overwriting files on the student's computer.

**Comment by jathak** [comment]
Does the `/user/email/get_backups` endpoint on the server include backups the user's partner makes or is it just the backups they make themselves? If it doesn't include partner backups, which API should I use instead to get those?

**Comment by Sumukh** [comment]
It includes the partners. That's the same endpoint that the website hits to get the list of backups.

**Comment by soumyabasu** [comment]
It includes backups from their partner (source: https://github.com/Cal-CS-61A-Staff/ok/blob/master/server/app/models.py#L231).

**Comment by jathak** [comment]
I've implemented Option B in #92.

**Comment by jathak** [comment]
#92 has been merged, so this can be closed.
