### ISSUE TITLE
README should say how to deploy a new version

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok-client#82]
Some instructions for updating `ok` would be helpful:

- Where's the version number
- How does `setup.py` work

**Comment by albert12132** [comment]
Deploying a new version involves knowing the password to okpy's pypi account. I can write some instructions on how to deploy with the assumption that the person updating knows the password. How should we determine who should know the password?

**Comment by papajohn** [comment]
I think only you know the password right now. How about we make a Google
doc full of secrets. It can be shared with head tas and instructors.
