### ISSUE TITLE
ExportProtocol mistakenly reports "Download failed" on second attempt

### ISSUE THREAD

**Issue by albert12132** [Cal-CS-61A-Staff/ok-client#84]
@jathak I tried using the --export command as an admin. I was able to download the submissions to a `submissions` directory. On a second invocation, however, it reports that the Download failed. I'm not sure why this error is occurring.

**Comment by jathak** [comment]
Was this after all submissions were downloaded or was it resuming based on `export_cache.pkl`?

**Comment by albert12132** [comment]
All submissions were download on the first invocation. In the start of the second invocation, there the `submissions` directory exists, and no `export_cache.pkl` file exists. The second invocation then reports "Download failed."
