### ISSUE TITLE
Should GradingProtocol stop at the first failed test case?

### ISSUE THREAD

**Issue by albert12132** [Cal-CS-61A-Staff/ok-client#96]
This used to be the behavior of ok-client. I removed it a while ago because I thought it would be better to show students all failed tests so that they get a better sense of their progress, but now I'm having second thoughts, since all the test output can be overwhelming. Thoughts?

**Comment by alvinwan** [comment]
I'd vote for restoring it; scrolling through the woes of clearly-wrong (and unimplemented methods) could be troublesome.
